### ISSUE TITLE
[Design Flaw / Suggestion] Rewards in wrong category [ver 9.2-063] 

### ISSUE THREAD

**Issue by tflo** [TLDRMissions/TLDRMissions#247]
Most of the rewards listed in the Sanctum Feature category as sub-selectables don’t belong to that category.

IMO, only the Sanctum-Feature-related rewards should go there, that is: 
- Superior Parts (Necro)
- Infused Ruby (Venthyr)
- Medallion of Service (Kyrian)
- The different Queen’s Spirits (Night Fae)

Most of the other stuff that currently is there is either zone-related (e.g. Sinstone Fragments) or completely generic (e.g. Phaedrum Ore, Spiritual Healing Potion). The fact that this “other” stuff predominantly (or exclusively?) appears with the Venthyr missions doesn’t make it Sanctum Feature related.

~~As it is now, if I’m only interested in the Sanctum Feature stuff (as listed above), I would have to uncheck more than 20 items on each of my 12 Mission toons.~~

Suggestion: Make a “Miscellaneous” category and put that non-Sanctum-Feature, generic stuff there. It seems there is enough space in the GUI for an additional category.

Thanks for considering,

– Tom

---

Edit: Just realized that the subitems are stored in the profile, so forget the “unchecking on 12 toons” part from above. Nevertheless, a “Miscellaneous” category for the non-Sanctum-Feature stuff would be welcome.

**Comment by teelolws** [comment]
The long list of Profession items are, indeed, Venthyr only. Venthyr get offered them because they're needed for the RSVP quests in the Ember Court.

Before -063 all the items were just included in the Sanctum Feature option. I added the subcategory due to request from another player: https://github.com/TLDRMissions/TLDRMissions/issues/230

I can look into breaking that menu down into subsubcategories by covenant. Maybe one for Ventyhr/Currencies + Venthyr/Items

**Comment by teelolws** [comment]
They do, just not from the mission table. Necrolords get them from the weekly quests in the Sitchyard. Infact all covenants get little profession rewards like that from their Feature, I guess Venthyr get extra?
