### ISSUE TITLE
Venthyr missions STILL taking exceedingly long calculation times [BUG] Other

### ISSUE THREAD

**Issue by dilvishdamned** [TLDRMissions/TLDRMissions#282]
![image](https://user-images.githubusercontent.com/60253285/170783935-ea17c735-9d39-47aa-8652-8fe3ff3d5de7.png)
This capped out at 30k attempts/simulations & several others go just about this high...previously I stating this bug & we agreed a certain anima thieves mission was to blame, but it's happening again with Corrupted Builders...for whatever reason Venthyr missions require a massive amount of calculations

**Comment by teelolws** [comment]
Because Venthyr troops just aren't good, compared to the other covenants. Its long been agreed that Night Fae troops are just way better than the others. But Blizzard doesn't seem interesting in balancing them, or fixing the 300 other bugs with followers/troops/enemies that I've spotted while making this addon.

Look at the Venture Plan box for that mission its trying to simulate. Corrupted Builders. You can see that yellow triangle with the !. Even Venture Plan is telling you that mission is too hard for Venthyr.

Its a level 60 mission. What level are your troops?

**Comment by dilvishdamned** [comment]
Yeah I agree.  The troops suck & no good healers.  All my troops are lvl 60.  We're hitting 30k attempts again on Corpselice Spawnlings mission  
![image](https://user-images.githubusercontent.com/60253285/171164529-a975ca94-c46d-48e8-902c-b03fb89b0200.png)

**Comment by teelolws** [comment]
Yup, cause its just a hard mission it can't find a solution for. Theres nothing I can do about that. Blame Blizzard for making Venthyr troops suck compared to the others.
