### ISSUE TITLE
Question about sim speed and performance between TLDR and VP

### ISSUE THREAD

**Issue by Nillx** [TLDRMissions/TLDRMissions#352]
I currently have it set to 6 sims per frame and sometimes im getting a noticeable FPS hit (around 20-40fps) while when i try to sim missions with VP i  always get down to 47fps from 120 locked. Also VP is simming missions a lot faster so im wondering why is that? I guess its using a different sim system?

**Comment by teelolws** [comment]
I write the simulation engine from scratch. The Venture Plan simulation engine was completely unreadable, probably written like this deliberately so the original author is the only one who can make changes. I admit, my simulator could be more efficient in some aspects. It should only matter if you're actually trying to do other stuff while running the simulator, though. Most of us just turn it on then look away until its done.

VP sims faster because you're picking the followers for it. So you've already done the majority of the work. TLDR has to pick followers, and if you have a roster of 20 followers, the first step is trying to find the best follower, which is a lot of overhead over VP which doesn't need to do this.

**Comment by Nillx** [comment]
Fair enough, thanks for the info. Its shame that the VP author left the addon in state like this not letting anyone modify it  or use stuff from it but on well. Even a bit slower than VP your addon is still better and saves more time!
