### ISSUE TITLE
[BUG] Other

### ISSUE THREAD

**Issue by LostTemple1990** [TLDRMissions/TLDRMissions#358]
here are two logs generated by vp which show that sim will select different units from real log when taunter is existed(according to your source code)
[Log1-TauntForCleave.txt](https://github.com/TLDRMissions/TLDRMissions/files/8857727/Log1-TauntForCleave.txt)
in turn 9,log shows that unit 0 cast a cleave spell to 7,11(unit 11 is taunter) but did not cast to unit 10 (they all existed in field)

[Log2-TauntForCone.txt](https://github.com/TLDRMissions/TLDRMissions/files/8857756/Log2-TauntForCone.txt)
in turn 9,log shows that unit 0 cast a cone spell to 6,10,11(unit 11 is taunter) 
PriorityPair for cone spell may be correct for taunter but the logic of taunter for cleave spell should be check
btw. log2 was generated before patch 9.25 ,perhaps you may have to modify the value of spell 85 to what is was in 9.2 to check the log
I want more logs to check out the logic of taunter too
would you please to share more logs(any format is ok) of taunter to help check the taunter logic?

**Comment by teelolws** [comment]
It wasn't checking for taunt because `affectedByTaunt = true,` was not set for spell ID 22.

From log 1 I can see that unit 8 was also on the board. 7+8+10+11, taunted by 11, targetted 7+11.

For log 2: spell ID 312, "cone" would normally target 5, so we can confirm that attack should be affected by taunt. I will update `affectedByTaunt` for 312. I'll add some code so "cone" attacks can support taunt.
