### ISSUE TITLE
Feature Request: Length of Mission

### ISSUE THREAD

**Issue by rhodan412** [TLDRMissions/TLDRMissions#386]
**TLDR Version of your idea**
TLDR version:  9.2-092

**Slightly longer version**

**Additional context**
Would you consider adding the length of the mission time in the TLDR UI.  
I.E. Mission (9/10) Invasive Action (14 hrs)
...

While it's nice to have a limit on the mission duration, under the Advanced Tab, it might be helpful to note how much time a certain mission might take for the reward being shown.

**Comment by teelolws** [comment]
Next patch:
![image](https://user-images.githubusercontent.com/49792789/174479820-b716c35d-9925-416b-b220-72f34409526c.png)

![image](https://user-images.githubusercontent.com/49792789/174479945-5ca6dda9-60ec-4659-a694-73d5e85a6df0.png)

`(%dh)` was the best I could find in GlobalStrings https://github.com/tekkub/wow-globalstrings/blob/master/GlobalStrings/enUS.lua with just hours, no seconds, no minutes, so that I won't have to get the translators involved.
