### ISSUE TITLE
Suggestions: "Finish Completed Missions" button changes

### ISSUE THREAD

**Issue by bjg123456** [TLDRMissions/TLDRMissions#415]
Could the button be moved to a more intuitive position?  Items at the bottom of a window are usually clicked last, but in this case, it's the first thing most people click.

Could the button be enlarged so it's easier to notice and click?  That would also make the text easier to read.  It looks strangely crowded into that lower-left corner as of now. 

Is it possible to make the button disappear immediately after all rewards have been collected?  While the "Done!" feels rewarding, it looks like a button we're supposed to click to make it disappear, but that only results in the "Not yet" error.  Feels bad lol.

Thanks for considering!

**Comment by teelolws** [comment]
Hm. I've already moved the button before and don't want to do it again. It used to be at the top-right corner, but I had to move it to make room for the other options. If I move it again, it will only confuse people used to finding the button at the top-left corner now.

While I can make the button bigger, its not so easy to make the text inside it bigger, due to limitations of what the game lets me do. I'll consider lowering the time the button lingers for. The delay is intentional - give the player the chance to acknowledge that its finished, and they can move on to starting missions.

**Comment by teelolws** [comment]
I'll make it slightly bigger, about 120% of what it was before. Any bigger and its too obnoxious, imo.
![image](https://user-images.githubusercontent.com/49792789/175797312-c823d4a5-38ef-40fe-879f-c2598ed45c1f.png)

Not going to move it. Don't want to confuse users used to its positioning.

**Comment by bjg123456** [comment]
Thank you for considering my suggestions and for making this change!  I think the larger button helps.  If you end up deciding to revert the button size, you might consider changing it from left-aligned to center-aligned instead.  That would also help set it apart.

Just wanted to thank you for this wonderful addon, as well.  It's made mission tables playable again.  From the ashes of Venture Plan drama rises a superior product.  Take care!
