### ISSUE TITLE
[BUG] Other - "Then, send followers to fail for XP" ignored campaign progress and didn't fail

### ISSUE THREAD

**Issue by Saxayone** [TLDRMissions/TLDRMissions#503]
I'm using the "Then, send followers to fail for XP" option but it seems to have ignored campaign progress requirement or expected the mission to fail but it succeeded instead. =/

Only had 1~12 selected and now the character is on 16 due to sending for the past few days.

**Comment by teelolws** [comment]
I've already sent out all my missions today, so I can't test it. See if this fixes that:
[TLDRMissions.zip](https://github.com/TLDRMissions/TLDRMissions/files/9203746/TLDRMissions.zip)

**Comment by Saxayone** [comment]
I'll try it when I can but I'm in the same position, just sent them.

**Comment by Saxayone** [comment]
![Screenshot 2022-07-28 064102](https://user-images.githubusercontent.com/47307427/181429292-583a44a0-d28b-4367-a1fb-9832f8ca8b75.png)

Seems like it still wants to send campaign missions when it's not selected,
It doesn't send if the option for fully disabling campaign missions is met however it kinda defeats the whole purpose of setting a maximum.

The whole reason of that setting is to level the table through the campaign and stop at a certain point, for it to be ignored by an arguably less important setting makes it seem pointless.

As it stands, it will always send campaign missions that might fail for xp but as followers level there is a higher chance of success and the campaign will slowly become completed. The only way around it is to either not have the "follower xp" setting active until you reach the desired level then manually flip it to never send campaign missions or always have campaign missions disabled and manually level them to the desired level.

**Comment by teelolws** [comment]
I suggest you change Campaign to an exclusion, with only 13-16 and 17+ checked. Then, allow the lower Campaign missions to be sent using "anything else for XP".

I cannot change the submenus to have both inclusions and exclusions. The submenus use DropDownMenus which is Blizzards code, so I am limited with how much I can change.

**Comment by Saxayone** [comment]
That is basically what I've done for my lower campaign characters/tracking & manually sending campaign as-well for a bit.

However, it does unfortunately feel like it will be rather unintuitive solution for others that may end up in the same situation.

Maybe a tooltip for the sending "else for xp" advising it may send campaign if not specifically disabled?

**Comment by teelolws** [comment]
Well... it says "anything else for XP". Anything means **anything**. I shouldn't have to explain that further.

If a mission sent using "sacrifice for XP" succeeds then that is unfortunate. However, ever since I added that option I have advised against it. I don't consider 500XP to be worth the time and anima. But I added the option anyway due to a number of requests.

I built this addon with "solve and send missions as fast as possible" in mind. I didn't build it considering everyones "except don't send that, or that, or that" strategies. But I've provided you the means to exclude them anyway. Some of them might be obvious. Some of them, you might need to think about. But the means are there.
