### ISSUE TITLE
[BUG] Other: Addon only seems to consider one troop type (the top one)

### ISSUE THREAD

**Issue by AddonWhiner** [TLDRMissions/TLDRMissions#505]
On my Kyrian, it always uses Halberdiers. On my Night Fae, it always uses Grovetenders. The latter is especially bothersome as Trappers are super strong.

**Comment by teelolws** [comment]
It will take a combination that will beat the mission. If a full team of the first troop beats it, then it doesn't need to test the other troop. If a full team of the first troop doesn't beat the mission, then it will test combinations of troops. You're just not seeing this happen because the chances of 4 Grovetenders failing but 4 Trappers succeeding is relatively small. Give it enough time, you'll see it send other troops.

**Comment by AddonWhiner** [comment]
Yeah, it did happen now, so you're right. But something else is an issue then because there was a mission that met my criteria for desirable missions that it didn't seem to want to do, and I figured it was because it didn't want to send Trappers, because I could and did beat that mission by sending a hero and Trappers. If I encounter that again I will be sure to open a more appropriate issue.
