### ISSUE TITLE
Right solution to show missing followers?

### ISSUE THREAD

**Issue by drinkeboer** [TLDRMissions/TLDRMissions#515]
As of version 9.2-118b I'm missing two followers I did not collect yet.
As a test I enabled the last two lines in followerlist.lua.

>     GarrisonLandingPageFollowerList.UpdateData = newUpdateData
>     CovenantMissionFrame.FollowerList.UpdateData = newUpdateData
> 

Now they show up again.
![image](https://user-images.githubusercontent.com/31187366/182337687-02837671-6703-4b15-b8ee-3e1383da1791.png)

Is this the correct "fix" ?

**Comment by teelolws** [comment]
I had to remove the missing followers bit from the Mission table's list, due to causing errors while in combat. The list is still there on your report frame - the button next to your minimap. You should comment those two lines back out again, or you'll get errors while in combat.

![image](https://user-images.githubusercontent.com/49792789/182338762-00646416-76d7-4efc-aaed-b0c22593f003.png)


![image](https://user-images.githubusercontent.com/49792789/182338781-6d8cb80d-46d8-4120-8a68-c48279d7cd2c.png)

**Comment by drinkeboer** [comment]
Thanks for the explanation, will do so.
